{% set name = "mumax3c" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1ed0d1928259204819e3a7d283682e5b1d9388b1f1c6b69851fab6425eebaef2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - micromagneticmodel >=0.63.2
    - micromagnetictests >=0.63.1
    - scipy
    - ubermagtable >=0.61.3
    - ubermagutil >=0.63.2

test:
  imports:
    - mumax3c
  commands:
    - pip check
    # running unittests would require a GPU and a separate Mumax3 installation
  requires:
    - pip

about:
  home: http://ubermag.github.io/
  summary: Python interface to mumax3 integrated into Jupyter notebook.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://ubermag.github.io/documentation/mumax3c.html
  dev_url: https://github.com/ubermag/mumax3c

extra:
  recipe-maintainers:
    - fangohr
    - lang-m
    - samjrholt
    - swapneelap
